export { default as Routines } from './Routines'
export { default as Home } from './Home'
// export { default as Search } from './Search'
export { default as Activities } from './Activities'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as AddActivity } from './AddActivity'
export { default as AddRoutine } from './AddRoutine'
export { default as MyRoutines } from './MyRoutines'
export { default as UpdateRoutineForm } from './UpdateRoutineForm'
// export { default as RoutineView } from './RoutineView'
// export { default as Routine } from './Routine'